### PR TITLE
#2331 fix bug in size of yS numpy array when simulation stops early

### LINKED ISSUE #2331: [Bug]: IDAKLU solver sensitivity calculation
### PyBaMM Version

22.8

### Python Version

3.9

### Describe the bug

Sensitivities with respect to `Negative electrode diffusivity [m2.s-1]` and `Positive electrode diffusivity [m2.s-1]` found by IDAKLU solver are 0 for SPMe model with Chen 2020 parameter values, C/10 constant current discharge

### Steps to Reproduce

```
import pybamm
import numpy as np

model = pybamm.lithium_ion.SPMe()

param = pybamm.ParameterValues("Chen2020")
param["Negative electrode diffusivity [m2.s-1]"] = pybamm.InputParameter("Ds_n")
param["Positive electrode diffusivity [m2.s-1]"] = pybamm.InputParameter("Ds_p")
param["Electrolyte diffusivity [m2.s-1]"] = pybamm.InputParameter("De")


simulation = pybamm.Simulation(model, parameter_values=param, solver = pybamm.IDAKLUSolver())


t_max = 60*60*10
t_eval = np.linspace(0, t_max, num=(t_max//2))

solution = simulation.solve(t_eval,
                            inputs={ "Ds_n": 3.54e-14, "Ds_p": 1.01e-13, "De": 3.71e-10}, 
                            calculate_sensitivities=True)

np.unique(solution.sensitivities['De'].flatten(), return_counts=True)

# resulting in all sensitivities = 0
np.unique(solution.sensitivities['Ds_n'].flatten(), return_counts=True)
np.unique(solution.sensitivities['Ds_p'].flatten(), return_counts=True)
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by martinjrobins**
# Description

fix bug in size of yS numpy array when simulation stops early

Fixes #2331 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

File: pybamm/solvers/c_solvers/idaklu_casadi.cpp [hunk 1]
```diff
@@ -373,6 +373,14 @@ int sensitivities_casadi(int Ns, realtype t, N_Vector yy, N_Vector yp,
...
   p_python_functions->sens();
 
+  //for (int i = 0; i < np; i++) {
+  //  std::cout << "dF/dp[" << i << "] = [";
+  //  for (int j = 0; j < p_python_functions->number_of_states; j++) {
+  //    std::cout << NV_DATA_S(resvalS[i])[j] << " ";
+  //  }
+  //  std::cout << "]" << std::endl;
+  //}
+
```
Comment (tinosulzer) [inline pybamm/solvers/c_solvers/idaklu_casadi.cpp:383]: remove?

**Review by tinosulzer — COMMENTED** [review]
Can you add a test where an event is triggered?

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@
 
 ## Bug fixes
 
+- For simulations with events that cause the simulation to stop early, the sensitivities could be evaluated incorrectly to zero ([#2331](https://github.com/pybamm-team/PyBaMM/pull/2337))
```
Comment (tinosulzer) [inline CHANGELOG.md:13]: should be in "Unreleased" section
